/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.venda;

import controller.ClienteController;
import controller.ProdutoController;
import controller.UsuarioController;
import controller.VendaController;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import model.Produto;
import model.Venda;
import model.Cliente;
import model.Usuario;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import model.ItemVenda;

public class frAltVenda extends javax.swing.JDialog {

    ArrayList<Produto> listaProdutos = new ArrayList<>();
    int ultimoProdAdd;
    int id;
    double soma;

    public frAltVenda(javax.swing.JDialog parent, boolean modal, int id) {
        super(parent, modal);
        initComponents();
        this.id = id;
        VendaController venC = new VendaController();
        Venda ven = venC.consultarVenda(id);
        txtCliente.setText(ven.getCliente());
        txtUsuario.setText(ven.getUsuario());
        txtVencimento.setText(String.valueOf(ven.getVencimento()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtCliente = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        btnConfirmar = new javax.swing.JButton();
        btnRemProduto = new javax.swing.JButton();
        btnAddProduto = new javax.swing.JButton();
        btnAltProduto = new javax.swing.JButton();
        txtVencimento = new javax.swing.JFormattedTextField();
        lblTotal = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSrcCliente = new javax.swing.JButton();
        btnSelUsuario = new javax.swing.JButton();
        cmbStatus = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Produto", "Quantidade", "Valor Unidade", "Valor Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProdutos);

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmarMouseClicked(evt);
            }
        });

        btnRemProduto.setText("Remover");
        btnRemProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemProdutoMouseClicked(evt);
            }
        });

        btnAddProduto.setText("Adcionar");
        btnAddProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddProdutoMouseClicked(evt);
            }
        });

        btnAltProduto.setText("Alterar");
        btnAltProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAltProdutoMouseClicked(evt);
            }
        });

        txtVencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        lblTotal.setBackground(new java.awt.Color(255, 255, 255));
        lblTotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblTotal.setText("Valor Total:");

        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cliente");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Vencimento");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Usuario");

        btnSrcCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSrcClienteMouseClicked(evt);
            }
        });

        btnSelUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSelUsuarioMouseClicked(evt);
            }
        });

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "valido", "quitado" }));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Status");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnRemProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAltProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 21, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSrcCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(txtVencimento))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbStatus, 0, 148, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtVencimento)
                                .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSrcCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                                .addComponent(btnSelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(btnRemProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(btnAddProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(btnAltProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSrcClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSrcClienteMouseClicked
        int value = new frSelCliente(this, rootPaneCheckingEnabled).getValue();
        txtCliente.setText(String.valueOf(value));
    }//GEN-LAST:event_btnSrcClienteMouseClicked

    private void btnSelUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelUsuarioMouseClicked
        int value = new frSelUsuario(this, rootPaneCheckingEnabled).getValue();
        txtUsuario.setText(String.valueOf(value));
    }//GEN-LAST:event_btnSelUsuarioMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnAddProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddProdutoMouseClicked
        DefaultTableModel modeloTabela = (DefaultTableModel) tblProdutos.getModel();
        ProdutoController prodC = new ProdutoController();
        int[] value = new frSelProdutos(this, rootPaneCheckingEnabled).getValue();
        Produto prod = prodC.consultar(value[0]);

        Object[] linha = {
            prod.getId(),
            prod.getTitulo(),
            value[1],
            prod.getPreco(),
            prod.getPreco() * value[1],};
        modeloTabela.addRow(linha);
        listaProdutos.add(prod);
        ultimoProdAdd = prod.getId();
        recalcularTotal();
    }//GEN-LAST:event_btnAddProdutoMouseClicked

    private void btnAltProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltProdutoMouseClicked
        DefaultTableModel modeloTabela = (DefaultTableModel) tblProdutos.getModel();
        ProdutoController prodC = new ProdutoController();
        if (tblProdutos.getSelectedRow() != -1) {
            int linhaSelecionada = tblProdutos.getSelectedRow();

            String textoCelula = tblProdutos.getValueAt(linhaSelecionada, 0).toString();
            ArrayList<Integer> value = new frAltProdutos(this, rootPaneCheckingEnabled).getValue();
            Produto prod = prodC.consultar(value.get(0));

            modeloTabela.setValueAt(prod.getId(), linhaSelecionada, 0);
            modeloTabela.setValueAt(prod.getTitulo(), linhaSelecionada, 1);
            modeloTabela.setValueAt(value.get(1), linhaSelecionada, 2);
            modeloTabela.setValueAt(prod.getPreco(), linhaSelecionada, 3);
            modeloTabela.setValueAt(prod.getPreco() * value.get(1), linhaSelecionada, 4);

            for (int i = listaProdutos.size() - 1; i >= 0; i--) {
                if (listaProdutos.get(i).getId() == ultimoProdAdd) {
                    listaProdutos.remove(i);
                }
            }

            listaProdutos.add(prod);
            ultimoProdAdd = prod.getId();
            JOptionPane.showMessageDialog(null, listaProdutos);
            recalcularTotal();

        } else {
            JOptionPane.showMessageDialog(null, "Nenhum produto selecionada");
        }

    }//GEN-LAST:event_btnAltProdutoMouseClicked

    private void btnRemProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemProdutoMouseClicked
        ProdutoController prodC = new ProdutoController();
        if (tblProdutos.getSelectedRow() != -1) {
            DefaultTableModel modeloTabela = (DefaultTableModel) tblProdutos.getModel();
            int linhaSelecionada = tblProdutos.getSelectedRow();
            String textoCelula = tblProdutos.getValueAt(linhaSelecionada, 0).toString();
            if (JOptionPane.showConfirmDialog(null, "tem certeza que deseja excluir esse item?") == 0) {
                modeloTabela.removeRow(linhaSelecionada);
                for (int i = listaProdutos.size() - 1; i >= 0; i--) {
                    if (listaProdutos.get(i).getId() == ultimoProdAdd) {
                        listaProdutos.remove(i);
                    }
                }
            }
        }
        recalcularTotal();
    }//GEN-LAST:event_btnRemProdutoMouseClicked

    private void btnConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarMouseClicked
        VendaController venC = new VendaController();
        Venda ven = new Venda();
        DefaultTableModel modelo = (DefaultTableModel) tblProdutos.getModel();
        double soma = 0.0;

        for (int i = 0; i < modelo.getRowCount(); i++) {
            Object valorCelula = modelo.getValueAt(i, 4); // Coluna 5 = índice 4
            if (valorCelula != null) {
                try {
                    soma += Double.parseDouble(valorCelula.toString());
                } catch (NumberFormatException e) {
                    System.out.println("Valor inválido na linha " + i + ": " + valorCelula);
                }
            }
        }
        ven.setClienteId(Integer.parseInt(txtCliente.getText()));
        ven.setUsuarioId(Integer.parseInt(txtUsuario.getText()));
        ven.setTotal(soma);
        try {
            String texto = txtVencimento.getText();
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy"); // ou o formato que você estiver usando
            Date utilDate = sdf.parse(texto); // java.util.Date
            java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime()); // java.sql.Date

            ven.setVencimento(sqlDate);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data inválida! Use o formato dd/MM/yyyy.");
            e.printStackTrace();
        }
        ven.setStatus((String) cmbStatus.getSelectedItem());
        ven.setItens(listaProdutos);

        if (venC.alterarVenda(ven, id)) {
            JOptionPane.showMessageDialog(null, "venda alterada com sucesso");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao alterar a venda");
        }
    }//GEN-LAST:event_btnConfirmarMouseClicked

    private void recalcularTotal() {
        soma = 0.0;
        DefaultTableModel modelo = (DefaultTableModel) tblProdutos.getModel();
        for (int i = 0; i < modelo.getRowCount(); i++) {
            Object valorCelula = modelo.getValueAt(i, 4);
            if (valorCelula != null) {
                try {
                    soma += Double.parseDouble(valorCelula.toString());
                } catch (NumberFormatException e) {
                    System.out.println("Erro de número na linha " + i);
                }
            }
        }
        lblTotal.setText("Valor Total: " + soma);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frAltVenda.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frAltVenda.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frAltVenda.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frAltVenda.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frAltVenda dialog = new frAltVenda(new javax.swing.JDialog(), true, 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduto;
    private javax.swing.JButton btnAltProduto;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnRemProduto;
    private javax.swing.JButton btnSelUsuario;
    private javax.swing.JButton btnSrcCliente;
    public javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JFormattedTextField txtVencimento;
    // End of variables declaration//GEN-END:variables
}
